/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package opcionesfoto;

import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Alfre
 */
public class Ejercicio extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio
     */
    StringBuffer choices;

    public Ejercicio() {
        initComponents();
        choices = new StringBuffer("hgl");
        pictureLabel.setText("");
        updatePicture();
        pack();
    }

    /**
     * Listens to the check boxes.
     */
    public void cambiaChoices(int index, char c) {
        choices.setCharAt(index, c);
        updatePicture();
    }

    protected void updatePicture() {
        //Get the icon corresponding to the image.
        ImageIcon prueba = new ImageIcon("images/foto-"
                + choices.toString()
                + ".gif");
        pictureLabel.setIcon(prueba);
        if (prueba == null) {
            pictureLabel.setText("Missing Image");
        } else {
            pictureLabel.setText(null);
        }
    }

    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = Ejercicio.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("No encontrado: " + path);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Genero = new javax.swing.ButtonGroup();
        jPGenero = new javax.swing.JPanel();
        jRBHombre = new javax.swing.JRadioButton();
        jRBMujer = new javax.swing.JRadioButton();
        jPOpciones = new javax.swing.JPanel();
        jCBLargo = new javax.swing.JCheckBox();
        jCBGafas = new javax.swing.JCheckBox();
        pictureLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPGenero.setLayout(new java.awt.GridBagLayout());

        Genero.add(jRBHombre);
        jRBHombre.setSelected(true);
        jRBHombre.setText("Hombre");
        jRBHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBHombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPGenero.add(jRBHombre, gridBagConstraints);

        Genero.add(jRBMujer);
        jRBMujer.setText("Mujer");
        jRBMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMujerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPGenero.add(jRBMujer, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPGenero, gridBagConstraints);

        jPOpciones.setLayout(new java.awt.GridBagLayout());

        jCBLargo.setSelected(true);
        jCBLargo.setText("Pelo Largo");
        jCBLargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBLargoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPOpciones.add(jCBLargo, gridBagConstraints);

        jCBGafas.setSelected(true);
        jCBGafas.setText("Gafas");
        jCBGafas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGafasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPOpciones.add(jCBGafas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPOpciones, gridBagConstraints);

        pictureLabel.setText("a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(pictureLabel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBHombreActionPerformed
        cambiaChoices(0, 'h');
    }//GEN-LAST:event_jRBHombreActionPerformed

    private void jRBMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMujerActionPerformed
        cambiaChoices(0, 'm');
    }//GEN-LAST:event_jRBMujerActionPerformed

    private void jCBGafasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGafasActionPerformed
        char c = '-';

        if (jCBGafas.isSelected()) {
            c = 'g';
        }

        cambiaChoices(1, c);
    }//GEN-LAST:event_jCBGafasActionPerformed

    private void jCBLargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBLargoActionPerformed
        char c = '-';

        if (jCBLargo.isSelected()) {
            c = 'l';
        }

        cambiaChoices(2, c);
    }//GEN-LAST:event_jCBLargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Genero;
    private javax.swing.JCheckBox jCBGafas;
    private javax.swing.JCheckBox jCBLargo;
    private javax.swing.JPanel jPGenero;
    private javax.swing.JPanel jPOpciones;
    private javax.swing.JRadioButton jRBHombre;
    private javax.swing.JRadioButton jRBMujer;
    private javax.swing.JLabel pictureLabel;
    // End of variables declaration//GEN-END:variables
}
